author: yyds666
title: yyds666 · Mihomo / Clash / Surge 配置集合

type: collection
language:
  - zh-CN
  - en-US

project:
  name: Self-Configuration
  url: https://github.com/666OS/YYDS
  description: >
    作者 yyds666 长期维护的代理配置集合，
    覆盖 Mihomo / Clash Meta / Surge，
    提供从新手到专业用户的多层级方案。

contact:
  telegram: https://t.me/Pinched666

license: MIT
updated: 2025-12-06

badges:
  - label: Mihomo
    value: Config
    color: blue
  - label: Clash
    value: Meta
    color: blue
  - label: Surge
    value: v5
    color: orange
  - label: License
    value: MIT
    color: green

features:
  common:
    - Fake-IP DNS
    - IPv6 支持
    - QUIC 阻止
    - Sniffer 流量嗅探
    - 自动规则更新
    - 多地区节点正则筛选
  advanced:
    - Smart 智能策略（LightGBM）
    - 多层策略架构
    - 权重策略选择
    - 中转代理（部分配置）
    - 多端口监听（部分配置）

clients:
  mihomo:
    supported: true
    panel: Zashboard
    controller: 127.0.0.1:9090
  clash:
    supported: true
    variants:
      - Clash Meta
      - Clash for Windows
      - Stash
      - FlClash
  surge:
    supported: true
    platform:
      - iOS
      - macOS

rule_sources:
  - name: dler-io Rules
    url: https://github.com/dler-io/Rules
  - name: blackmatrix7 ios_rule_script
    url: https://github.com/blackmatrix7/ios_rule_script
  - name: SukkaW Surge
    url: https://github.com/SukkaW/Surge
  - name: VirgilClyne ASN
    url: https://github.com/VirgilClyne/GetSomeFries
  - name: TikTok Unlock
    url: https://github.com/Semporia/TikTok-Unlock

conventions:
  proxy_ports:
    http: 7890
    socks5: 7891
    mixed: 7893
  auth:
    username: mihomo
    password: yyds666
  dns:
    enhanced_mode: fake-ip
    ipv6: true
  update_interval:
    ruleset: 86400
    proxy_provider: 3600

readme:
  sections:
    - overview
    - file_comparison
    - feature_matrix
    - usage
    - faq
    - changelog
